cmake/extensions/CMakeLists.txt
A different source file, closures.c, includes dlmalloc.c but sets
various preprocessor defines before doing so to make sure it's built
appropriately.  Building a seperate dlmalloc.c.o can possibly generate
incorectly defined and conflicting symbols.
=> libffi: Avoid clash with builtin malloc and libc malloc

CMakeLists.txt
CMake 3.0 introduced policy CMP0042 ("MACOSX_RPATH is enabled by default"). When building on OS X this results in warnings like:
CMake Warning (dev):
Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
--help-policy CMP0042" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
MACOSX_RPATH is not specified for the following targets:
extension_array
extension_audioop
extension_binascii
[...]
This commit hides those warnings.
=> Hide CMake policy CMP0042 warnings

.travis.yml
By updating the version of openssl used on travis, this commit fixes the
following error:
//----------
Traceback (most recent call last):
File "/home/travis/build/python-cmake-buildsystem/python-cmake-buildsystem-build/lib/python2.7/test/regrtest.py", line 159, in <module>
import random
File "/home/travis/build/python-cmake-buildsystem/python-cmake-buildsystem-build/lib/python2.7/random.py", line 49, in <module>
import hashlib as _hashlib
File "/home/travis/build/python-cmake-buildsystem/python-cmake-buildsystem-build/lib/python2.7/hashlib.py", line 138, in <module>
_hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
//----------
... caused when using the following options:
[cmake …
=> Fix openssl_md_meth_names error reported on travis

circle.yml
This commit fixes a regression introduced in 9d43b16, it renames
remaining references to thewtex images.
=> circle: Fix build renaming all image references

cmake/extensions/CMakeLists.txt
When compiling Python 3.5.2 I received the following error:
```
CMakeFiles/_freeze_importlib.dir/__/__/CMakeFiles/config.c.o:(.data+0x4a8): undefined reference to 'PyInit_dbm'
CMakeFiles/_freeze_importlib.dir/__/__/CMakeFiles/config.c.o:(.data+0x4b8): undefined reference to 'PyInit_gdbm'
```
Investigation of the extensions cmake file showed that dbm and gdbm were not named correctly to produce the correct PyInit function call.
I added a little logic to change the name depending on Py 2.x vs Py 3.x. All tests pass after compile.
=> Fixed error in naming of dbm and gdbm modules with Python 3.x

cmake/ConfigureChecks.cmake
Reported by Martin Oberhuber as V7COR-4651
=> ConfigureChecks: VxWorks:  Disable _XOPEN_SOURCE due to "sys/select.h" failing

CMakeLists.txt
Python's package installation tools (pip and friends) expect `ABIFLAGS` to be part of these directory names.
=> Correctly name the installed include and library configuration directories.

CMakeLists.txt
When an external Python source directory is provided using the SRC_DIR
option, make sure to extract the Python version from that source before
applying patches.
=> Fix applying patches when external source is provided

CMakeLists.txt
The commit updates the build system so that any python version explicitly
passed using -DSRC_DIR:PATH=/path/to/src is accepted.
Report a fatal error only when no source directory is explicitly passed and
the python version selected passing -DPYTHON_VERSION:STRING=X.Y.Z is unknown.
Reported-by: @johnmudd
=> cmake: Accept configuring against any python version

cmake/PythonApplyPatches.cmake
=> Use upper case *_FOUND variables when locating `patch`

cmake/lib/CMakeLists.txt
This commit ensures the Grammar generation (current happening at install
time) can complete no system without python already installed on the system.
It fixes error like the following:
-- Up-to-date: /work/Preview/Slicer-0-build/python-install/include/python2.7/pyconfig.h
/path/to/python-install/bin/python: error while loading shared libraries: libpython2.7.so: cannot open shared object file: No such file or directory
/path/to/python-install/bin/python: error while loading shared libraries: libpython2.7.so: cannot open shared object file: No such file or directory
=> Fix install on system without python already on the system

cmake/extensions/CMakeLists.txt
Per upstream [documentation](https://docs.python.org/2/library/sqlite3.html#f1):
> The sqlite3 module is not built with loadable extension support by
> default, because some platforms (notably Mac OS X) have SQLite
> libraries which are compiled without this feature. To get loadable
> extension support, you must modify setup.py and remove the line that
> sets SQLITE_OMIT_LOAD_EXTENSION.
which means that SQLITE_OMIT_LOAD_EXTENSION is added as a compile
definition by default in the upstream build system. We match that
here to fix `import sqlite3`.
=> Fix sqlite3 import by matching upstream build option for load_extension

cmake/extensions/CMakeLists.txt
From [What's New in Python 3.6](https://docs.python.org/3/whatsnew/3.6.html): 
> The hashlib module received support for the BLAKE2, SHA-3 and SHAKE hash algorithms...
This PR builds the required `_blake2` and `_sha3` extension modules.
=> Python 3.6 provides `_blake2` and `_sha3` modules for `hashlib`.

cmake/libpython/CMakeLists.txt
This was originally PR #153 which then became part of PR #178 that was closed with the comment that the associated changes had been integrated into commit c16eba7. However the code to ensure that the stub library is built was dropped along the way -- Ninja still reports `ninja: error: 'libs/python3stub.lib', needed by 'bin/python3.dll', missing and no known rule to make it`.
=> Ensure DLL stub library is built for Windows.

cmake/ConfigureChecks.cmake
This commit was adapted from the work done by @sitsofe in
https://github.com/axboe/fio/pull/309/commits/ccf2d89d39b21bc8c7b497b40be5b82eadb80863
Description below was copied verbatim from the commit referenced above.
macOS 10.12 introduced support for clock_gettime() but when compiling
with Xcode 8 (or later) and targeting 10.11 (or older) the clock_gettime
symbol is now found at configure/compile time but referenced weakly.
Running the created binary on 10.11 results in a "dyld: lazy symbol
binding failed: Symbol not found: _clock_gettime" error.
Options for working around this issue include:
1. Turn references to functions that might be weak into compilation
errors (-Werror=partial-availability).
2. Disable visibility of functions that might be weak at compile link
time …
=> cmake: Disable weak linking to "fix Symbol not found: _clock_gettime"

patches/3.6/0004-Fix-Windows-build-of-Python-for-latest-WinSDK.patch, patches/3.6/README.rst
VS 2017 has a new Windows SDK
iomodule.c needs windows.h to compile
this supplies a patch to add window.h to the module
related
[Fix CMake Build for MSVC 15 2017 #233](https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/issues/233)
=> patch - fix iomodule.c for VS 2017

CMakeLists.txt, appveyor.yml, cmake/PythonApplyPatches.cmake, patches/2.7.15/Windows-MSVC/1600/0001-VS2010-Support-Backport-Fix-13210.-Port-the-Windows-.patch, patches/2.7.15/Windows-MSVC/1700/0001-VS2010-Support-Backport-Fix-13210.-Port-the-Windows-.patch, patches/2.7.15/Windows-MSVC/1800/0001-VS2010-Support-Backport-Fix-13210.-Port-the-Windows-.patch, patches/2.7.15/Windows-MSVC/1900/0001-VS2010-Support-Backport-Fix-13210.-Port-the-Windows-.patch, patches/2.7.15/Windows-MSVC/1900/0002-VS2015-Support-Backport-Issue-22919-Windows-build-up.patch, patches/2.7.15/Windows-MSVC/1900/0003-VS2015-Support-Backport-of-Issue-23524-Replace-_PyVe.patch, patches/2.7.15/Windows-MSVC/README.rst
I made a few small changes to get it working with Python 2.7.15.
- fileio.c doesn't need the patch from MSVC 1900, an equivalent change was made in 2.7.15
- line numbers of the changes in timemodule.c have changed in 2.7.15
- some changes were needed to use 2.7.13 patches for 2.7.14 also and then apply 2.7.15 patches to that version and higher
=> Add support for Python 2.7.15

cmake/ConfigureChecks.cmake, cmake/extensions/CMakeLists.txt
glibc has removed Sun RPC. Use replacement libtirpc headers and library in
nis moduleupdated path for rpc.h for systems using libtirpc
See https://github.com/python/cpython/pull/5137
This closes #224
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillion@kitware.com>
=> cmake: Support building nis module on system having libtirpc

README.rst, cmake/ConfigureChecks.cmake, cmake/extensions/CMakeLists.txt
A number of of Python packages complained that lzma package was not available (displayed a warning or refused to load), such as pandas, skimage, meshio.
Now if LZMA_LIBRARY:FILEPATH and LZMA_INCLUDE_PATH:PATH CMake variables are set then Python is build with lzma support.
Tested with lzma implementation that uses CMake build system: https://github.com/nextgis-borsch/lib_lzma.git
=> Add support for building with lzma

cmake/extensions/CMakeLists.txt
LZMA extension is now supported.
If it is not too late, you may amend the last commit with this.
=> Remove irrelevant comment

CMakeLists.txt
This commit restores the support for specifying DESTDIR
env. variable when building "install" target associated
with "Unix Makefiles" generated build-system:
```
$ DESTIR=/path/to/install make install
```
See https://cmake.org/cmake/help/latest/envvar/DESTDIR.html
=> Fix install specifying DESTDIR env. var

cmake/ConfigureChecks.cmake
This commit is a follow-up of f929319a9 (cmake: Fix undefined reference to
gss_* symbols when WITH_STATIC_DEPENDENCIES is ON).
If the shared library "libgssapi_krb5.so" can't be found, the build-system
is updated to assume the static libraries are required.
Indeed, without installing the "libkrb5-dev" package, the shared library
"libgssapi_krb5.so" can't be found and the test checking if the tirpc
library was build with or without the gssapi feature can not be performed.
See #227 and #285
=> cmake: Fix undefined reference to gss_* symbols when libkrb5-dev package not installed

cmake/config-unix/pyconfig.h.in
This commit fixes a regression introduced in 97631f223 (Add support for
building Python 3.7.x) where it was incorrectly assumed that PYTHONFRAMEWORK
existed for Python 3.6.
It turns out that the prior value in pyconfig.h.in was introduced
in python/cpython@a8f8d5b4b (bpo-29585: optimize site.py startup time (GH-136))
while working toward cpython 3.7 and just before python/cpython@6b42eb176
(bpo-29585: Fix sysconfig.get_config_var("PYTHONFRAMEWORK") (GH-2483)) intoducing
_PYTHONFRAMEWORK and avoiding incorrect value returned by sysconfig.get_config_var.
Co-authored-by: Issam E. Maghni <issam.e.maghni@mailbox.org>
=> 3.7.x: Fix incorrect PYTHONFRAMEWORK value returned by sysconfig.get_config_var

cmake/extensions/CMakeLists.txt
This commit fixes a regression introduced in e0017a7 (3.6.x: Add support
for building _testconsole module) ensuring the module is excluded on platform
different from windows.
It fixes the following error when building with BUILD_EXTENSIONS_AS_BUILTIN
enabled on Linux:
```
CMakeFiles/_freeze_importlib.dir/__/__/CMakeFiles/config.c.o:(.data+0x308): undefined reference to `PyInit__testconsole'
```
=> _testconsole: Fix link error when attempting to build extension as builtin on Linux

.circleci/config.yml, .github/workflows/CI.yml, CMakeLists.txt, README.rst
This is a followup PR to what was discussed at https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/306#issuecomment-1015978067. 
This updates the ci builds to use the latest patch release of each python minor release and also updates the default built to the latest patch release of the latest python minor version currently supported (3.9).
=> Use latest patch versions for testing and default version

.github/workflows/CI.yml
See https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
=> ci: Fix macos build using "macos-latest" instead of obsolete "macos-10.15"

cmake/extensions/CMakeLists.txt
Changed USE_SYSTEM_FFI to USE_SYSTEM_LibFFI in tocmake/extensions/CmakeList.txt.
This is to be consistent with the changes in commit 48bb6d758bb86
=> rename USE_SYSTEM_FFI to USE_SYSTEM_LibFFI

CMakeLists.txt
This typo prevents USE_SYSTEM_LIBRARIES from enabling sqlite3 in the final build without explicitly setting USE_SYSTEM_SQLite3
=> fix USE_SYSTEM_SQLite3 case

CMakeLists.txt
This commit ensures that the `SRC_DIR` set after extracting the Python source archive is also converted to an absolute path during the initial configuration.
=> cmake: Prevent rebuild ensuring SRC_DIR always converted to absolute path

cmake/ConfigureChecks.cmake
Note that patches have not been updated
Based of:
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/340
=> style: Strip trailing spaces from CMake files

cmake/ConfigureChecks.cmake, cmake/extensions/CMakeLists.txt
When linking against a system libmpdec (e.g. one built locally and installed under /usr/local/lib), libraries are not currently being discovered or linked correctly. This patch informs cmake to:
- search for library `mpdec` (since cmake will prepend the `lib` prefix automatically)
- use the discovered libraries when linking the `_decimal` module
=> Fix use of system libmpdec

cmake/ConfigureChecks.cmake, cmake/lib/CMakeLists.txt
'linux2' used to refer to the Linux 2.X kernel, but sys.platform was
changed to just 'linux' for all kernel versions since Python 3.3 circa
2011.
See also: https://github.com/python/cpython/issues/56535
=> cmake: sys.platform should be 'linux' instead of 'linux2'

CTestConfig.cmake
Address error like the following on Windows:
```
[...]
Submit files
Send to group: Circle-CI-Windows
SubmitURL: http://
Set CURLOPT_SSLVERSION to CURL_SSLVERSION_TLSv1_2
Set CURLOPT_SSL_VERIFYPEER to on
Upload file: C:/Users/circleci/project/build/Testing/20250415-1739/Test.xml to http://?FileName=circleci-window___3.9.17-x64-Release_#349_52b4f06___20250415-1739-Circle-CI-Windows___XML___Test.xml&build=3.9.17-x64-Release_%23349_52b4f06&site=circleci-window&stamp=20250415-1739-Circle-CI-Windows&MD5=7b920eab13b41b1c986459474c1525e9 Size: 1042
Error when uploading file: C:/Users/circleci/project/build/Testing/20250415-1739/Test.xml
Error message was: URL rejected: No host part in the URL
Problems when submitting via HTTP
[...]
```
And like the following on Linux:
```
[...] …
```
=> cmake: Fix CDash submission updating CTestConfig to use https

CMakeLists.txt, cmake/ConfigureChecks.cmake, cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt
* Removes use of `IS_PY3` and replaces both `${PY3_BUILTIN}` and `${PY3_ALWAYS_BUILTIN}` respectively with `BUILTIN` and `ALWAYS_BUILTIN`.
* Fixes logic setting target properties: Attempt to set target properties only if target was effectively added. Checking if the `ENABLE_<upper_extension_name>` is set to ON only indicates that the extension was requested.
=> cmake: Simplify removing use of IS_PY3, PY3_BUILTIN and PY3_ALWAYS_BUILTIN

cmake/config-mingw/pyconfig.h, cmake/config-unix/pyconfig.h.in
Follow-up of 6391889 ("cmake: Remove support for building CPython 2.7", 2025-04-28) introduced through:
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/352
=> cmake: Remove obsolete defines from pyconfig.h and pyconfig.h.in

CMakeLists.txt
Follow-up of 97631f2 ("Add support for building Python 3.7.x", 2022-01-05) Since threading is always built-in with Python >= 3.7, the warning message has been updated accordingly.
=> cmake: Fix warning reported when setting WITH_THREAD with Python < 3.7

CMakeLists.txt
Adapted from changes originally integrated through:
* https://github.com/bjia56/portable-python-cmake-buildsystem/pull/37
* #350
=> cmake: Fix execution of cmakescript tests when integrating as a subproject

cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt, cmake/python/CMakeLists.txt
This commit removes setting of the following variables:
- `OBJECT2_SOURCES`
- `PYTHON2_COMMON_SOURCES`
- `PGEN2_SOURCES`
- `_multiprocessing2_SOURCES`
- `bz2_2_NAME`
- `subdir_2`
Follow-up of 6391889 ("cmake: Remove support for building CPython 2.7", 2025-04-28)
=> cmake: Remove setting of obsolete variables specific to Python 2

.github/dependabot.yml, .github/workflows/CI.yml, .gitignore
Summary:
* Add Dependabot workflow to update GitHub Actions
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions
* Pin GitHub actions to full length commit SHA
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
* #350
=> Pin GitHub Actions and add Dependabot workflow to update GitHub Actions

CMakeLists.txt
This is consistent with the default value specified in the autoconf system.
=> cmake: Fix macOS build setting USE_SYSTEM_LIBMPDEC default value to OFF

cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt
Leverage CMake 3.20+ generator expressions to replace conditional `if()/list(APPEND)` blocks and streamline source inclusion.
=> cmake: Simplify logic using generator expressions

cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt, cmake/python/CMakeLists.txt
Remove the following variables from `cmake/python/CMakeLists.txt`:
* `subdir_3`
Remove the following variables from `cmake/extensions/CMakeLists.txt`:
* `crypt3_NAME`
* `datetime3_NAME` and `datetime3_SOURCES`
* `time_SOURCES`
* `thread3_NAME` and `thread3_SOURCES`
* `winreg3_NAME`
* `bz2_3_NAME`
* `dbm3_SOURCES` and `dbm_name`
* `gdbm3_SOURCES` and `gdbm_name`
Rename the following variables in `cmake/libpython/CMakeLists.txt`:
* `init_return_type_3` -> `init_return_type`
* `init_prefix_3` -> `init_prefix`
--- 
Also fix `extension_time` source by associating `_time.c` if Python is 3.2: Follow-up of 7b6b8fa ("datetime, time: Fix build conditionally including _time.c or timemodule.c", 2022-01-18)
=> Simplify removing versioned variables 

cmake/extensions/CMakeLists.txt
This is done anticipating upcoming updates to support specific Python version by updating the argument associated with the `REQUIRES` argument associated with `add_python_extension` CMake function.
Follow-up of c978a31 ("style: Indent add_python_extension parameters anticipating updates", 2025-05-01) introduced in:
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/370
=> style: Indent add_python_extension parameters anticipating updates (part 2)

cmake/extensions/CMakeLists.txt
* Simplify extension build-system using genex to include `_time.c`
* Rename `is_py33_or_greater` to `IS_PY3_3_OR_GREATER`
=> Extension simplify and use genex

cmake/ConfigureChecks.cmake, cmake/config-mingw/pyconfig.h, cmake/config-unix/pyconfig.h.in, cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt, cmake/python/CMakeLists.txt
* Re-introduce unicode defines to support to support Python 3.0 to 3.2: Partially reverts b979b95 ("cmake: Remove obsolete defines from pyconfig.h and pyconfig.h.in", 2025-04-29) and 6391889 ("cmake: Remove support for building CPython 2.7", 2025-04-28).
* Attempt to fix build for Python 3.0 to 3.5: In an attempt to workaround issue to link against newer openssl library, extensions `_ssl` and `_hashlib` have been excluded for Python < 3.5
=> Attempt to fix support for python 3.0 to 3.5

.github/workflows/CI.yml
Adapted from similar changes introduced in the `scikit-build/scikit-build-core` project.
For more details, see https://github.com/re-actors/alls-green
=> ci: Streamline branch protection setup adding "pass" job to GitHub workflow

cmake/extensions/CMakeLists.txt
The existing use of VERSION_EQUAL assumed a patch version of `.0` (e.g. `3.2.0`), which breaks for any `3.2.x` release. Change the comparison to use only the major and minor components (e.g. `3.2`) so that all patch‐level variants are correctly recognized.
Fix regression originally introduced in the following commits:
* 7b6b8fa ("datetime, time: Fix build conditionally including _time.c or timemodule.c", 2022-01-18)
* 39e9d3d ("cmake: Simplify removing versioned variables", 2025-05-01)
* 8943355 ("cmake: Simplify extension build-system using genex to include _time.c", 2025-05-05)
* #350
Follow-up of:
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/371
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/373
=> cmake: Fix VERSION_EQUAL checks to compare only major.minor

cmake/Extensions.cmake
For example, instead of `lib-dynload.so`, the library `readline.cpython-38-x86_64-linux-gnu.so` is generated.
=> cmake: Starting with Python3.8, append SOABI to extension shared library name

cmake/ConfigureChecks.cmake
* Requirement for 8.4 introduced in python/cpython@6716d60cec7 ("Issue #22085: Dropped support of Tk 8.3 in Tkinter.", 2014-07-30)
* Requirement for 8.3.1 introduced in python/cpython@6691772ff6c ("Merged revisions 69474 via svnmerge from svn+ssh://pythondev/python/trunk", 2009-02-09)
=> ConfigureChecks: Check for minimum Tk version

.circleci/config.yml, .github/workflows/CI.yml, CMakeLists.txt, README.rst, cmake/ConfigureChecks.cmake, cmake/config-mingw/pyconfig.h, cmake/config-unix/pyconfig.h.in, cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt, patches/3.11/0001-_bootstrap_python-Fix-execution-on-windows-disabling.patch, patches/3.11/README.rst
* Add checksums for Python 3.11.0 to 3.11.12
* Set default python version to 3.11.12
* Switch from `c99` to `c11`
* Add convenience target `deepfreeze_modules` for regenerating download the deepfreeze sources
* Check that TCL is at least 8.5.12
dbm extension:
* Add support for `GDBM_COMPAT` introducing `NDBM_USE` variable set to either
`NDBM` or `GDBM_COMPAT`. See python/cpython@0a9f69539be ("bpo-45747: Detect gdbm/dbm dependencies in configure (GH-29467)", 2021-11-10)
Updated pyconfig.h.in
* Add the following for which there was already a configure check.
- Headers:
- `HAVE_BZLIB_H`
- `HAVE_DB_H`
- `HAVE_GDBM_DASH_NDBM_H`
- `HAVE_GDBM_H`
- `HAVE_GDBM_NDBM_H`
- `HAVE_LZMA_H`
- `HAVE_NDBM_H`
- `HAVE_NETDB_H`
- `HAVE_NETINET_IN_H`
- `HAVE_RPC_RPC_H`
- `HAVE_ZLIB_H`
- Library:
- `HAVE_LIBDB` …
=> Add support for building Python 3.11.x

.git-blame-ignore-revs, .gitignore
This file lists revisions that should be ignored when considering attribution for the actual code written.  Code style changes should not be considered as modifications with regards to attribution.
To see clean and meaningful blame information:
```
$ git blame important.py --ignore-revs-file .git-blame-ignore-revs
```
To configure git to automatically ignore revisions listed in a file on every call to `git blame`.
```
$ git config blame.ignoreRevsFile `.git-blame-ignore-revs`
```
Adapted from InsightSoftwareConsortium/ITK@3a969e556
=> style: Improve attribution by ignoring bulk formatting

cmake/extensions/CMakeLists.txt
Starting with python/cpython@38f331d4656 ("bpo-45898: Remove duplicate symbols from _ctypes/cfield.c (GH-29791)", 2022-02-24), `FFI_BUILDING` is removed. Note that while the use of `FFI_BUILDING` seems to be specific to windows, backward compatibility is maintained defining it for all platforms.
---
* #350
=> fix(extension_ctypes): Conditionally define FFI_BUILDING

cmake/config-unix/pyconfig.h.in
Fix regression introduced in 5a6d5ec ("cmake/config-unix/pyconfig.h.in: Define RETSIGTYPE to void", 2025-05-16)
----------
* #350
=> fix(pyconfig): Do not redefine RETSIGTYPE

cmake/ConfigureChecks.cmake
Follow-up of 2a9c3805dde ("closes bpo-34585: Don't do runtime test to get float byte order. (GH-9085)", 2018-09-19)
----------
* #350
=> ConfigureChecks: Add HAVE_FLOAT_WORDS_BIGENDIAN check

cmake/extensions/CMakeLists.txt
Starting with Python 3.10, the macro `Py_LIMITED_API` is defined in `xxlimited.c`. See python/cpython@240bcf82a11 ("bpo-41111: xxlimited.c defines Py_LIMITED_API (GH-25151)", 2021-04-02)
----------
* #350
=> extension_xxlimited: Fix Py_LIMITED_API redefinition warning

CMakeLists.txt, cmake/UnitTests.cmake
This update ensures that only tests requiring supported resources are executed. Specifically:
* Introduces `SUPPORTED_TEST_RESOURCES` (defaulting to `network`) and uses it to drive both test filtering and the `-u` option passed to `regrtest.py`.
* Updates `UnitTests.cmake` to parse unindented `support.requires(...)` calls in test scripts, extracting the first argument (i.e., the required resource).
* Skips any test that requires a resource not listed in `SUPPORTED_TEST_RESOURCES`.
* Adds support for hardcoded resource mappings (e.g., for tests like `test_zipfile64` where the `requires(...)` call spans multiple lines).
* Emits informative messages when tests are skipped due to unmet resource requirements.
Example of output for Python 3.11:
```
[...]
-- Supported test resources: network
-- …
```
=> test: Filter tests based on support.requires(...) and supported resources

patches/3.6.15/0001-bpo-35519-Rename-test.bisect-to-test.bisect_cmd-GH-1.patch, patches/3.6.15/README.rst
Add 3.6.15 patch based of python/cpython@62a68b762a4 ("bpo-31784: Use time.time_ns() in uuid.uuid1() (GH-11189)", 2018-12-18)
----------
* #350
=> tests: fix 3.6.15 tests ensuring bisect module can be imported

.circleci/config.yml, .github/workflows/CI.yml, CMakeLists.txt, README.rst, cmake/ConfigureChecks.cmake, cmake/config-unix/pyconfig.h.in, cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt, patches/3.12/0001-_bootstrap_python-Fix-execution-on-windows-disabling.patch, patches/3.12/0002-getpath-Update-build-directory-assumptions-based-on-.patch, patches/3.12/README.rst
* Add checksums for Python 3.12.0 to 3.12.10
* Set default python version to 3.12.10
* Fix windows _bootstrap_python build generating custom "config_minimal.c". This also required adding 3.12 patch to work around the lack of `sys.winver`. See python-cmake-buildsystem/cpython@ca2fd1a7856 ("_bootstrap_python: Fix execution on windows disabling site import", 2025-05-13)
_bootstrap_python:
* Fix windows build updating `config_minimal.c` including `_typing`. Follow-up of 5683458 ("cmake: Fix windows _bootstrap_python build generating custom "config_minimal.c"", 2025-05-13)
ctypes extension:
* Introduce `HAVE_FFI_CALL` set to 1 only if the `ffi_call` symbol is found. This allows to implement the logic similar to the one introduced in autoconf.
* On macOS, the extension requires to be built …
=> Add support for building Python 3.12x

cmake/extensions/CMakeLists.txt
Linking against the static `ffi_static` library on Windows requires defining `FFI_BUILDING` to avoid linkage issues, as documented in `ffi.h`.
This change restores the behavior that was inadvertently disabled in commit 6478bf3 ("fix(extension_ctypes): Conditionally define FFI_BUILDING", 2025-05-22), ensuring correct linkage for static builds.
Additionally, the `HAVE_FFI_CALL` requirement is now restricted to Unix platforms, where the corresponding configure check is performed in `ConfigureChecks.cmake`.
----------
* #350
=> fix(extension_ctypes): Define FFI_BUILDING for static libffi on Windows

cmake/libpython/CMakeLists.txt
Due to CMake's lack of support for generator expressions in the `SOURCE` argument of `set_property()`, compile definitions associated with sources cannot be reliably applied via set_property() when conditional logic is used.
See https://gitlab.kitware.com/cmake/cmake/-/issues/26993
This patch documents the issue and ensures that compile definitions from built-in extensions are explicitly propagated to relevant targets using `target_compile_definitions()`, preserving intended build behavior.
----------
* #350
=> fix: Work around CMake issue #26993 explicitly propagating extension definitions

cmake/extensions/CMakeLists.txt, cmake/libpython/CMakeLists.txt
Fixes warnings when passing narrow string literals to Windows APIs expecting wide strings:
```
C:\path\to\Python-3.12.10\Python\dynload_win.c(191,27): warning C4133: 'function': incompatible types - from 'char [8]
' to 'const wchar_t *' [C:\path\to\pycbs-3.12-build\CMakeBuild\libpython\libpython-shared.vcxproj]
```
Ensures PY3_DLLNAME is consistently defined with the wide string modifier (`L`) across relevant CMake sections.
----------
* #350
=> fix: Define PY3_DLLNAME as wide string to fix C4133 warnings

CMakeLists.txt, cmake/PC/launcher/CMakeLists.txt, cmake/PythonExtractVersionInfo.cmake
This pull request adds support for building the following Windows-specific Python launchers:
* `venvlauncher` and `venvwlauncher`. Introduced in Python ≥ 3.3, but only built when Python ≥ 3.9 to simplify resource handling.
* `pylauncher` and `pywlauncher`. Introduced and built when Python ≥ 3.11.
These launchers rely on `launcher.c` and `launcher2.c`, depending on the target. They enable Python-specific runtime behavior for virtual environments and support shebang redirection on Windows.
To avoid build issues related to the `_WINDOWS` macro being implicitly defined via `/D_WINDOWS` (e.g., from `CMAKE_C_FLAGS`), we introduce a helper function:
```cmake
_add_executable_without_windows(target_name ...)
```
This function:
* Adds the executable target using `add_executable(...)`
* Explicitly …
=> Fix `test_venv` on Windows adding support for building python launchers 
